# Generated by Django 2.1.3 on 2018-12-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='environmental_agency_flood_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=40)),
                ('town', models.CharField(max_length=40)),
                ('river', models.CharField(max_length=40)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('long', models.DecimalField(decimal_places=7, max_digits=10)),
                ('reading', models.FloatField()),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MqttWaterLevelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_serial', models.CharField(max_length=20)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('altitude', models.IntegerField()),
                ('river_height_mm', models.CharField(max_length=6)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MQTT', 'MQTT service'), ('REST', 'Environment Agency Real Time flood-monitoring API'), ('FLOOD', 'Flood warning')], max_length=5)),
                ('message', models.CharField(max_length=1000)),
                ('severity_rating', models.IntegerField()),
                ('severity_message', models.CharField(max_length=40)),
                ('time', models.DateTimeField(null=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='test_environmental_agency_flood_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=40)),
                ('town', models.CharField(max_length=40)),
                ('river', models.CharField(max_length=40)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('long', models.DecimalField(decimal_places=7, max_digits=10)),
                ('reading', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mqttwaterleveldata',
            unique_together={('time', 'hardware_serial')},
        ),
    ]
