# Generated by Django 2.1.4 on 2018-12-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_monitoring_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttwaterleveldata',
            name='altitude',
            field=models.IntegerField(),
        ),
    ]
