# Generated by Django 2.1.3 on 2018-12-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_monitoring_system', '0002_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
