# Generated by Django 2.1.4 on 2018-12-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_monitoring_system', '0003_auto_20181205_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttwaterleveldata',
            name='river_height_mm',
            field=models.CharField(max_length=6),
        ),
    ]
