# Generated by Django 2.1.3 on 2018-12-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_monitoring_system', '0004_auto_20181210_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_environmental_agency_flood_data',
            name='station',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
