# Generated by Django 2.1.3 on 2018-12-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_monitoring_system', '0004_auto_20181205_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='environmental_agency_flood_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=40)),
                ('town', models.CharField(max_length=40)),
                ('river', models.CharField(max_length=40)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('long', models.DecimalField(decimal_places=7, max_digits=10)),
                ('reading', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
