# Generated by Django 2.1.3 on 2018-12-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_monitoring_system', '0005_environmental_agency_flood_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sam_Mqtt_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_serial', models.CharField(max_length=20)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('altitude', models.IntegerField()),
                ('river_height_mm', models.CharField(max_length=6)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
