# Generated by Django 2.1.4 on 2018-12-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flood_monitoring_system', '0005_auto_20181205_1741'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mqttwaterleveldata',
            unique_together={('time', 'hardware_serial')},
        ),
    ]
