# Generated by Django 2.1.3 on 2018-12-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_monitoring_system', '0005_test_environmental_agency_flood_data_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
