# Generated by Django 2.1.3 on 2018-12-06 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flood_monitoring_system', '0006_sam_mqtt_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sam_Mqtt_Test',
            new_name='Sam_Mqtt',
        ),
    ]
