# Generated by Django 2.1.3 on 2018-12-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_monitoring_system', '0006_auto_20181210_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='label',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
