# Generated by Django 2.1.3 on 2018-12-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_monitoring_system', '0007_auto_20181206_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sam_mqtt',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
