# Generated by Django 2.1.3 on 2018-12-11 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flood_monitoring_system', '0007_subscriptions_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flood_monitoring_system.User'),
        ),
    ]
