# Generated by Django 2.1.3 on 2018-12-11 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flood_monitoring_system', '0008_auto_20181211_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='flood_monitoring_system.User'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
    ]
