# Generated by Django 2.1.3 on 2018-12-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_monitoring_system', '0009_auto_20181206_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sam_mqtt',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
